[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"
authors = ['Kirill Aksenov aksenovki@gmail.com']

[dependencies]
  rand = "0.3.14"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
